name: Update ASF APIs
on:
  push:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-asf:
    name: Update ASF APIs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Open Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up system wide dependencies
        run: |
          echo "xxxx" >> README.md

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Update ASF APIs"
          body: "xxxx"
          branch: "asf-auto-updates"
          author: "LocalStack Bot <localstack-bot@users.noreply.github.com>"
          committer: "LocalStack Bot <localstack-bot@users.noreply.github.com>"
          commit-message: "update generated ASF APIs to latest version"
          labels: "area: asf, area: dependencies, semver: patch"
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          reviewers: openimbot
